services:
  backend:
    ports:
      - "8797:8797"
    build: ./src/
    volumes:
    # билды под линукс
      - path_to_ffmpeg:/usr/local/bin/ffmpeg
      - path_to_ffprobe:/usr/local/bin/ffprobe
      - path_to_ffplay:/usr/local/bin/ffplay